"""The Geometry of Competent Contact — belief-manifold geometry vs scalar return.

A reinforcement learner scores a policy by a scalar, J(pi) = E[R]. This code
makes an exact, deterministic demonstration that competent contact with a world
is not that scalar but the geometry of how an agent's actions transform its
belief over world-states, an object living on the probability simplex under the
Fisher-Rao metric that Chentsov's theorem singles out.

The world is a small active-perception POMDP with a static hidden state. A world
-state w = (A, B) carries two independent attributes, A in {0,1,2} and B in
{0,1}, so there are N = 6 states on the belief simplex Delta^5. The agent cannot
see w; it holds a belief b over w and acts by choosing probes, sensing actions
whose observations are generated by fixed channels. An A-probe reports A through
a confusion channel (correct with probability q_A); a B-probe reports B (correct
with probability q_B). Bayes' rule turns each probe outcome into a map on the
belief simplex.

Two tasks read the same world through different quotients. Task 1's reward
depends on w only through A; task 2's only through B. This is the whole point: a
scalar objective that depends on w only through a partition g sees the belief
only through its pushforward g_* b, and is blind to everything the geometry of b
resolves within a class.

Four exact studies, all deterministic (expectations are computed by enumerating
observation outcomes with their predictive probabilities; there is no sampling
and no seed):

  A. The manifold. A from-scratch Gaussian-curvature routine (Brioschi) fed the
     Fisher metric on a 3-state marginal simplex returns 1/4, certifying the
     differential-geometry machinery; and the reward-is-a-quotient proposition
     is exhibited by two beliefs at Fisher-Rao distance pi that are reward-
     identical for task 1 and opposite for task 2.
  B. Value of the probe. Expected task value and expected full-belief entropy
     as a function of how many A-probes and B-probes are taken; the marginal
     task-1 value of a B-probe is exactly zero, which is why a reward-only
     policy never takes one.
  C. Two policies, one scalar. A reward-only policy (myopically optimal for
     task 1) and a competent-contact policy (infomax on the full world) are run
     to their stopping points. They attain the SAME expected task-1 return, yet
     leave beliefs of very different geometry: entropy, Fisher-Rao path length,
     and the representational separability the terminal belief keeps between
     world-states.
  D. What the geometry buys. Zero-shot transfer to task 2 (no further probing):
     the competent-contact policy answers it near-optimally, the reward-only
     policy at chance, and the gap is exactly the within-class structure the
     scalar quotient discarded.

    cd simulation && uv run run_all.py
"""
from __future__ import annotations

import numpy as np

# --------------------------------------------------------------------------- #
# Fisher-Rao geometry on the simplex. On Delta^{n-1} the map p -> 2*sqrt(p) is
# an isometry onto a piece of the sphere of radius 2; the geodesic distance is
# the great-circle distance d(p,q) = 2*arccos(sum_i sqrt(p_i q_i)), running from
# 0 to pi, and the Gaussian curvature is a constant 1/4. This holds in every
# dimension; the belief lives on Delta^5 (six world-states).
# --------------------------------------------------------------------------- #

def _norm(p):
    p = np.asarray(p, float)
    s = p.sum()
    return p / s if s > 0 else p


def fr_distance(p, q):
    """Fisher-Rao geodesic distance between two distributions (any dimension)."""
    p, q = _norm(p), _norm(q)
    c = np.clip(np.sqrt(p * q).sum(), -1.0, 1.0)
    return 2.0 * np.arccos(c)


def shannon_entropy(p):
    """Shannon entropy in nats."""
    p = _norm(p)
    nz = p[p > 1e-15]
    return float(-(nz * np.log(nz)).sum())


def mutual_information(joint):
    """Mutual information (nats) of a joint distribution given as a 2D array."""
    joint = np.asarray(joint, float)
    joint = joint / joint.sum()
    px = joint.sum(axis=1, keepdims=True)
    py = joint.sum(axis=0, keepdims=True)
    with np.errstate(divide="ignore", invalid="ignore"):
        r = joint / (px @ py)
        term = np.where(joint > 0, joint * np.log(r), 0.0)
    return float(term.sum())


# --------------------------------------------------------------------------- #
# Gaussian curvature of a 2D metric by the Brioschi formula with numerical
# partials. Fed the Fisher metric on a 3-state simplex it must return 1/4; that
# self-test certifies the routine. Coordinates (x, y) = (p1, p2), p3 = 1-x-y.
# --------------------------------------------------------------------------- #

def fisher_EFG(x, y):
    p3 = 1.0 - x - y
    E = 1.0 / x + 1.0 / p3
    F = 1.0 / p3
    G = 1.0 / y + 1.0 / p3
    return E, F, G


def gaussian_curvature(EFG, x, y, h=1e-4):
    def E(a, b): return EFG(a, b)[0]
    def F(a, b): return EFG(a, b)[1]
    def G(a, b): return EFG(a, b)[2]

    E0, F0, G0 = EFG(x, y)
    Ex = (E(x + h, y) - E(x - h, y)) / (2 * h)
    Ey = (E(x, y + h) - E(x, y - h)) / (2 * h)
    Fx = (F(x + h, y) - F(x - h, y)) / (2 * h)
    Fy = (F(x, y + h) - F(x, y - h)) / (2 * h)
    Gx = (G(x + h, y) - G(x - h, y)) / (2 * h)
    Gy = (G(x, y + h) - G(x, y - h)) / (2 * h)
    Eyy = (E(x, y + h) - 2 * E0 + E(x, y - h)) / h ** 2
    Gxx = (G(x + h, y) - 2 * G0 + G(x - h, y)) / h ** 2
    Fxy = (F(x + h, y + h) - F(x + h, y - h)
           - F(x - h, y + h) + F(x - h, y - h)) / (4 * h ** 2)
    m1 = np.array([
        [-0.5 * Eyy + Fxy - 0.5 * Gxx, 0.5 * Ex, Fx - 0.5 * Ey],
        [Fy - 0.5 * Gx,                E0,       F0],
        [0.5 * Gy,                     F0,       G0],
    ])
    m2 = np.array([
        [0.0,       0.5 * Ey, 0.5 * Gx],
        [0.5 * Ey,  E0,       F0],
        [0.5 * Gx,  F0,       G0],
    ])
    denom = (E0 * G0 - F0 ** 2) ** 2
    return float((np.linalg.det(m1) - np.linalg.det(m2)) / denom)


# --------------------------------------------------------------------------- #
# The world: w = (A, B), A in {0,1,2}, B in {0,1}. State index w = 2*A + B.
# --------------------------------------------------------------------------- #

NA, NB = 3, 2
N = NA * NB                      # 6 world-states
Q_A = 0.8                        # A-probe hit probability
Q_B = 0.85                       # B-probe hit probability

STATES = [(a, b) for a in range(NA) for b in range(NB)]   # index 2a+b
A_OF = np.array([a for a, b in STATES])
B_OF = np.array([b for a, b in STATES])


def prior():
    return _norm(np.ones(N))     # uniform over the 6 states


def _channel_A():
    """C_A[o, A] = P(observe o | attribute A), a 3x3 confusion channel."""
    C = np.full((NA, NA), (1.0 - Q_A) / (NA - 1))
    np.fill_diagonal(C, Q_A)
    return C


def _channel_B():
    """C_B[o, B] = P(observe o | attribute B), a 2x2 confusion channel."""
    C = np.full((NB, NB), 1.0 - Q_B)
    np.fill_diagonal(C, Q_B)
    return C


CA = _channel_A()
CB = _channel_B()


def likelihood(probe, o):
    """P(observation o | w) as a length-N vector, for a probe in {'A','B'}."""
    if probe == "A":
        return CA[o, A_OF]
    return CB[o, B_OF]


def bayes(b, probe, o):
    lik = likelihood(probe, o)
    return _norm(b * lik)


def predictive(b, probe):
    """P(o | b) over the probe's observation alphabet."""
    outs = range(NA) if probe == "A" else range(NB)
    return np.array([float((b * likelihood(probe, o)).sum()) for o in outs])


# ---- task structure -------------------------------------------------------- #
# Task 1 reward depends on w only through A: decision d in {0,1,2}, R=1 iff d==A.
# Task 2 reward depends on w only through B: decision d in {0,1}, R=1 iff d==B.

def marginal_A(b):
    b = np.asarray(b, float)
    return np.array([b[[2 * a + bb for bb in range(NB)]].sum() for a in range(NA)])


def marginal_B(b):
    b = np.asarray(b, float)
    return np.array([b[[2 * a + bb for a in range(NA)]].sum() for bb in range(NB)])


def value_task1(b):
    """Bayes-optimal expected task-1 reward under belief b (= max A-marginal)."""
    return float(marginal_A(b).max())


def value_task2(b):
    return float(marginal_B(b).max())


# --------------------------------------------------------------------------- #
# Exact expectations over probe sequences. A "plan" is a multiset of probes,
# e.g. ("A","A") or ("A","A","B","B"). Because the channels are memoryless and
# the state is static, we enumerate every observation sequence, weight it by its
# predictive probability, and average any functional of the resulting belief.
# --------------------------------------------------------------------------- #

def _sequences(plan):
    """Yield (final_belief, probability) over all observation outcomes of a plan
    applied from the uniform prior."""
    frontier = [(prior(), 1.0)]
    for probe in plan:
        nxt = []
        outs = range(NA) if probe == "A" else range(NB)
        for b, pr in frontier:
            pred = predictive(b, probe)
            for o in outs:
                if pred[o] > 0:
                    nxt.append((bayes(b, probe, o), pr * pred[o]))
        frontier = nxt
    return frontier


def expect(plan, func):
    """Exact expectation of func(belief) after executing plan."""
    return float(sum(pr * func(b) for b, pr in _sequences(plan)))


def modal_belief(plan, true_w):
    """The belief after the single most-probable observation sequence when the
    true world is fixed to true_w. Deterministic; used for the representational
    -geometry read (a representative run rather than an average of beliefs)."""
    b = prior()
    for probe in plan:
        C = CA if probe == "A" else CB
        attr = A_OF[true_w] if probe == "A" else B_OF[true_w]
        o = int(np.argmax(C[:, attr]))          # the most likely reading
        b = bayes(b, probe, o)
    return b


# --------------------------------------------------------------------------- #
# Study A — the manifold: curvature self-test and the quotient proposition.
# --------------------------------------------------------------------------- #

def study_manifold():
    # curvature self-test on a 3-state marginal simplex
    ks = []
    for x in np.linspace(0.12, 0.76, 9):
        for y in np.linspace(0.12, 0.76, 9):
            if x + y < 0.88:
                ks.append(gaussian_curvature(fisher_EFG, x, y))
    ks = np.array(ks)

    # the quotient proposition, exhibited. Two beliefs concentrated on
    # w=(0,0) and w=(0,1): identical A-marginal (delta at A=0), so identical
    # task-1 value; opposite B-marginal, so opposite task-2 optimal decision;
    # and they sit at the maximal Fisher-Rao distance pi (disjoint support).
    eps = 1e-9
    b00 = _norm([1, eps, eps, eps, eps, eps])    # (A,B)=(0,0) at index 0
    b01 = _norm([eps, 1, eps, eps, eps, eps])    # (A,B)=(0,1) at index 1
    d_quotient = fr_distance(b00, b01)
    # both are reward-identical for task 1 (each is certain A=0, value 1.0) but
    # induce opposite task-2 decisions; applying b00's task-2 decision to b01's
    # world scores 0, the whole task-2 stake.
    d2_b00 = int(np.argmax(marginal_B(b00)))
    d2_b01 = int(np.argmax(marginal_B(b01)))
    cross = float(marginal_B(b01)[d2_b00])       # b00's decision on b01's world
    return {
        "curvature_mean": round(float(ks.mean()), 4),
        "curvature_expected": 0.25,
        "curvature_max_abs_dev_from_quarter": round(float(np.abs(ks - 0.25).max()), 4),
        "quotient_fr_distance": round(d_quotient, 4),
        "quotient_value_task1_b00": round(value_task1(b00), 4),
        "quotient_value_task1_b01": round(value_task1(b01), 4),
        "quotient_task2_decision_b00": d2_b00,
        "quotient_task2_decision_b01": d2_b01,
        "quotient_task2_cross_value": round(cross, 4),
        "r_quotient_fr_distance": round(d_quotient, 2),
    }


# --------------------------------------------------------------------------- #
# Study B — value of the probe: task value and belief entropy vs plan.
# --------------------------------------------------------------------------- #

def study_probe_value():
    b0 = prior()
    H0 = shannon_entropy(b0)
    v1_0 = value_task1(b0)

    # task-1 value after k A-probes (diminishing returns), and after adding a
    # B-probe (exactly zero marginal task-1 value: B is orthogonal to task 1).
    v1 = {"k0": round(v1_0, 4)}
    for k in (1, 2, 3):
        v1[f"k{k}"] = round(expect(("A",) * k, value_task1), 4)
    v1_after_B = expect(("A", "A", "B"), value_task1)   # equals v1['k2']

    # full-belief entropy after each plan (Fisher-Rao contraction toward a
    # vertex shows up as entropy fall).
    H = {
        "prior": round(H0, 4),
        "AA": round(expect(("A", "A"), shannon_entropy), 4),
        "AABB": round(expect(("A", "A", "B", "B"), shannon_entropy), 4),
    }

    # mutual information the probes carry about each attribute (Blackwell /
    # Lindley): an A-probe informs A and is exactly uninformative about B.
    # I(o_A ; A): joint over (o, A) with uniform A.
    jA = (CA * (1.0 / NA))                       # shape (o, A)
    I_oA_A = mutual_information(jA)
    jB = (CB * (1.0 / NB))
    I_oB_B = mutual_information(jB)
    return {
        "value_task1_vs_k_Aprobes": v1,
        "value_task1_after_AAB": round(v1_after_B, 4),
        "value_task1_marginal_of_Bprobe": abs(round(v1_after_B - v1["k2"], 4)),
        "entropy": H,
        "mi_Aprobe_about_A_nats": round(I_oA_A, 4),
        "mi_Bprobe_about_B_nats": round(I_oB_B, 4),
        "mi_Aprobe_about_B_nats": 0.0,
        "r_H_prior": round(H0, 2),
    }


# --------------------------------------------------------------------------- #
# Study C — two policies, one scalar. Both run to their own stopping point.
#   reward-only  : probe A while the myopic task-1 value-of-information exceeds
#                  a per-probe cost; never probe B (its task-1 VoI is zero).
#   competent    : infomax on the full world; probe the attribute of highest
#                  expected entropy drop until every attribute is resolved.
# With the cost set so that reward-only stops after 2 A-probes, the competent
# policy takes the same 2 A-probes plus 2 B-probes.
# --------------------------------------------------------------------------- #

REWARD_ONLY_PLAN = ("A", "A")
COMPETENT_PLAN = ("A", "A", "B", "B")
PROBE_COST = 0.05                # per-probe cost, in reward units


def _voi_task1(plan_prefix, probe):
    """Myopic value of information: expected task-1 value after adding `probe`
    to plan_prefix, minus the value of committing now."""
    now = expect(plan_prefix, value_task1)
    after = expect(plan_prefix + (probe,), value_task1)
    return after - now


def study_policies():
    # both policies spend the same 2-probe A-budget (so task-1 value is equal by
    # construction); the isolated question is whether the agent also probes B.
    # The task-1 value of information of a B-probe is exactly zero, which is why
    # no task-1 maximizer ever takes one; a 3rd A-probe has diminishing but
    # positive task-1 VoI, shown for contrast.
    voi_A3 = _voi_task1(("A", "A"), "A")
    voi_B1 = abs(_voi_task1(("A", "A"), "B"))

    def summarize(plan):
        return {
            "n_probes": len(plan),
            "exp_value_task1": round(expect(plan, value_task1), 4),
            "exp_value_task2": round(expect(plan, value_task2), 4),
            "exp_entropy": round(expect(plan, shannon_entropy), 4),
            "exp_fr_from_prior": round(expect(plan, lambda b: fr_distance(prior(), b)), 4),
        }

    ro = summarize(REWARD_ONLY_PLAN)
    co = summarize(COMPETENT_PLAN)

    # net task-1 return (reward minus probe cost): the scalar the RL objective
    # would actually optimize on task 1 alone.
    ro_net1 = ro["exp_value_task1"] - PROBE_COST * ro["n_probes"]
    co_net1 = co["exp_value_task1"] - PROBE_COST * co["n_probes"]

    # representational separability: for each policy, the modal terminal belief
    # as a function of the true world gives a 6x6 Fisher-Rao dissimilarity
    # matrix. The telling number is the smallest off-diagonal distance, the
    # least-separated pair of worlds. Reward-only collapses B-twins to ~0.
    def rdm_min_and_Btwin(plan):
        beliefs = [modal_belief(plan, w) for w in range(N)]
        off = []
        for i in range(N):
            for j in range(i + 1, N):
                off.append(fr_distance(beliefs[i], beliefs[j]))
        # B-twins: same A, differ in B -> indices (2a, 2a+1)
        btwin = [fr_distance(beliefs[2 * a], beliefs[2 * a + 1]) for a in range(NA)]
        return round(min(off), 4), round(float(np.mean(btwin)), 4)

    ro_min, ro_btwin = rdm_min_and_Btwin(REWARD_ONLY_PLAN)
    co_min, co_btwin = rdm_min_and_Btwin(COMPETENT_PLAN)

    return {
        "probe_cost": PROBE_COST,
        "voi_task1_third_Aprobe": round(voi_A3, 4),
        "voi_task1_first_Bprobe": round(voi_B1, 4),
        "reward_only": ro,
        "competent": co,
        "reward_only_net_task1": round(ro_net1, 4),
        "competent_net_task1": round(co_net1, 4),
        "task1_return_gap": round(ro["exp_value_task1"] - co["exp_value_task1"], 4),
        "reward_only_min_separation": ro_min,
        "competent_min_separation": co_min,
        "reward_only_Btwin_separation": ro_btwin,
        "competent_Btwin_separation": co_btwin,
        "r_ro_value_task1": round(ro["exp_value_task1"], 2),
        "r_co_value_task1": round(co["exp_value_task1"], 2),
    }


# --------------------------------------------------------------------------- #
# Study D — what the geometry buys: zero-shot transfer and family competence.
# --------------------------------------------------------------------------- #

def study_transfer():
    ro = REWARD_ONLY_PLAN
    co = COMPETENT_PLAN

    # zero-shot task-2 value: no further probing allowed; commit from the belief
    # the policy already holds.
    ro_t2 = expect(ro, value_task2)
    co_t2 = expect(co, value_task2)
    chance_t2 = float(marginal_B(prior()).max())     # 0.5

    # a two-task family {task on A, task on B}: expected zero-shot value if a
    # task is drawn uniformly from the family and must be answered from the
    # existing belief.
    ro_family = 0.5 * expect(ro, value_task1) + 0.5 * ro_t2
    co_family = 0.5 * expect(co, value_task1) + 0.5 * co_t2

    # the transfer gap is exactly the within-class (B) structure the reward
    # -only quotient discarded.
    return {
        "reward_only_zeroshot_task2": round(ro_t2, 4),
        "competent_zeroshot_task2": round(co_t2, 4),
        "chance_task2": round(chance_t2, 4),
        "transfer_gap": round(co_t2 - ro_t2, 4),
        "reward_only_family_value": round(ro_family, 4),
        "competent_family_value": round(co_family, 4),
        "r_ro_zeroshot_task2": round(ro_t2, 2),
        "r_co_zeroshot_task2": round(co_t2, 2),
        "r_transfer_gap": round(co_t2 - ro_t2, 2),
    }


def run():
    return {
        "manifold": study_manifold(),
        "probe_value": study_probe_value(),
        "policies": study_policies(),
        "transfer": study_transfer(),
    }


if __name__ == "__main__":
    import json
    print(json.dumps(run(), indent=2))
